spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cache?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  #全局 若是值是null，就不会返回
  #  jackson:
  #    default-property-inclusion: non_null

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # 本地redis
  redis:
    host: 127.0.0.1
  cache:
      redis:
        timeToLive: 1000000

server:
  servlet:
    context-path: /cache
  port: 10011

